# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4fff7f9621d2bd3b4d57447b602321aa"
name = "gwp-cart-discount"
handle = "gwp-cart-discount"
application_url = "https://holdem-chest-restructuring-casa.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,read_products,write_discounts,write_products"

[auth]
redirect_urls = [
  "https://holdem-chest-restructuring-casa.trycloudflare.com/auth/callback",
  "https://holdem-chest-restructuring-casa.trycloudflare.com/auth/shopify/callback",
  "https://holdem-chest-restructuring-casa.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
